{% set version = "0.3" %}
{% set sha256 = "92a2b5bafd8ea59cd4fc5ab45b5d9defe91643d9b79d6863da492216dea8a9ba" %}

package:
  name: yacrd
  version: '{{version}}'

source:
  url: https://github.com/natir/yacrd/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0

requirements:
  build:
    - '{{ compiler("c") }}'
    - rust
  host:
    - xz
    - zlib
    - bzip2
  run:
    - xz
    - zlib
    - bzip2

test:
  commands:
    - yacrd -h

about:
  home: https://github.com/natir/yacrd
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Yet Another Chimeric Read Detector, with long-read mapper result as input.
